CREATE TABLE CUSTOMER(ID NUMBER, NAME VARCHAR(20), EMAIL VARCHAR(40), PHONE NUMBER, ADDRESS VARCHAR(80));


CREATE TABLE REPAIR(JOB_ID NUMBER, DATE_RECEIVED DATE, DUE_DATE DATE);


CREATE TABLE COMPUTER(SERIAL_NO NUMBER, MODEL VARCHAR(20), DETAILS VARCHAR(50));


CREATE TABLE TECHNICIAN(T_ID NUMBER, T_NAME VARCHAR(30), T_EMAIL VARCHAR(30), T_PHONE NUMBER);


CREATE TABLE ITEMS(HARDWARE_ID NUMBER, QUANTITY NUMBER, DEALER_ID NUMBER, PRICE NUMBER);


CREATE TABLE ACCOUNT(ACC_ID NUMBER);


CREATE TABLE BILL(BILL_NO NUMBER, DATE_OF_PAYMENT DATE, AMOUNT NUMBER);
